// ========================================================== ACT II — THE CLIMB

const T = (sq, en) => ({ sq, en });
const O = (label, hint, fx, res, extra = {}) => ({ label, hint, fx, res, ...extra });

const MID = [
  {
    id: 'seed_round', stage: [1, 6], once: true, weight: 8,
    req: (s) => s.revenue > 60000 && s.equity > 45,
    title: T('Raundi i investimit', 'The funding round'),
    body: T('Një fond të ofron kapital serioz. Me të vjen bordi, raportet tremujore dhe pritshmëria e rritjes 3x.',
            'A fund offers you serious capital. With it comes a board, quarterly reports and the expectation of 3x growth.'),
    opts: [
      O(T('Merr raundin e plotë', 'Take the full round'), T('Karburant maksimal, pronësi e prerë.', 'Maximum fuel, ownership cut.'),
        { cashU: 9, equity: -22, revMult: 1.35, influence: 14, valuation: 1.25, stress: 10, set: { hasBoard: true } },
        T('Llogaria nuk ka qenë kurrë kaq e plotë. Dhe kurrë nuk ke pasur kaq pak liri.',
          'The account has never been this full. And you have never had this little freedom.')),
      O(T('Raund i vogël', 'Small round'), T('Mjaftueshëm për të ecur, pa humbur timonin.', 'Enough to move, without losing the wheel.'),
        { cashU: 3.5, equity: -9, revMult: 1.14, influence: 6, valuation: 1.08 },
        T('Merr sa të duhet, jo sa të ofrohet. Disiplinë e rrallë.',
          'You take what you need, not what is offered. Rare discipline.')),
      O(T('Financo rritjen me fitim', 'Fund growth from profit'), T('E ngadaltë. E jotja.', 'Slow. Yours.'),
        { revMult: 1.04, rep: 6, stress: 6, set: { proudlyIndependent: true } },
        T('Rritesh me ritmin që lejon xhepi. Konkurrentët shkojnë më shpejt — për tani.',
          'You grow at the speed your pocket allows. Competitors move faster — for now.')),
    ],
  },
  {
    id: 'key_exec', stage: [2, 8], once: true, weight: 7,
    req: (s) => s.teamSize >= 5,
    title: T('Drejtuesi i dytë', 'The number two'),
    body: T('Kompania është shumë e madhe që ta mbash në kokë. Duhet dikush që vendos kur ti nuk je aty.',
            'The company is too big to hold in your head. You need someone who decides when you are not in the room.'),
    opts: [
      O(T('Sill dikë nga jashtë', 'Hire from outside'), T('Përvojë e provuar, kulturë e tronditur.', 'Proven experience, shaken culture.'),
        { cashU: -2, revMult: 1.18, morale: -8, stress: -14, costMult: 1.08 },
        T('Sjell sisteme që funksionojnë dhe një mënyrë pune që ekipi nuk e njeh.',
          'They bring systems that work and a way of working the team does not recognise.')),
      O(T('Ngrite dikë nga brenda', 'Promote from within'), T('Besnikëri dhe moral, boshllëk përvoje.', 'Loyalty and morale, an experience gap.'),
        { revMult: 1.08, morale: 16, rep: 4, stress: -8 },
        T('Ekipi sheh se rritja është e mundur këtu. Gabimet vijnë — por vijnë me zemër.',
          'The team sees that growth is possible here. They make mistakes, but they make them with heart.')),
      O(T('Mbaj gjithçka vetë', 'Keep it all yourself'), T('Kontroll, me çmimin e kokës tënde.', 'Control, at the cost of your head.'),
        { stress: 20, revMult: 0.98, morale: -6 },
        T('Asgjë nuk lëviz pa miratimin tënd. Përfshirë gjërat që s\'duhej të prisnin.',
          'Nothing moves without your approval. Including the things that should not have waited.')),
    ],
  },
  {
    id: 'expand_geo', stage: [2, 9], weight: 6,
    req: (s) => s.revenue > 250000,
    title: T('Tregu i dytë', 'The second market'),
    body: T('Rritja në shtëpi po ngadalësohet. Përtej kufirit ka treg — dhe rregulla që nuk i njeh.',
            'Growth at home is slowing. Across the border there is a market — and rules you do not know.'),
    opts: [
      O(T('Hap plotësisht', 'Full launch'), T('Investim i madh, rritje e madhe ose humbje e madhe.', 'Big spend, big growth or big loss.'),
        { cashU: -3.5, fixedCostU: 1.2, stress: 10 },
        T('Ekipi i ri nis punën në një qytet ku askush nuk e njeh markën tënde.',
          'A new team starts work in a city where nobody knows your brand.'),
        { risk: { p: 0.38,
          bad: { fx: { revU: -0.5, rep: -6, cashU: -1.2 }, res: T('Tregu nuk reagoi. Mbyll pas nëntë muajsh dhe mëson sa kushton arroganca.', 'The market did not respond. You shut it after nine months and learn what arrogance costs.') },
          good: { fx: { revU: 2.6, influence: 10, valuation: 1.15 }, res: T('Funksionon më mirë se në shtëpi. Tani je kompani me shumë tregje.', 'It works better than home. You are now a multi-market company.') } } }),
      O(T('Hyr me partner lokal', 'Enter with a local partner'), T('Më pak fitim, shumë më pak rrezik.', 'Less profit, far less risk.'),
        { revU: 1.2, marginAdd: -0.04, influence: 6, rep: 4 },
        T('Ata njohin çdo derë. Ti paguan për këtë njohuri — dhe ia vlen.',
          'They know every door. You pay for that knowledge — and it is worth it.')),
      O(T('Përqendrohu në shtëpi', 'Double down at home'), T('Thellësi në vend të gjerësisë.', 'Depth instead of breadth.'),
        { marginAdd: 0.05, revMult: 1.06, rep: 4, stress: -4 },
        T('Bëhesh i pazëvendësueshëm aty ku je, në vend që të jesh mediokër në dy vende.',
          'You become irreplaceable where you are, instead of mediocre in two places.')),
    ],
  },
  {
    id: 'quality_crisis', stage: [1, 9], weight: 6,
    req: (s) => s.revenue > 120000,
    title: T('Defekti', 'The defect'),
    body: T('Diçka nuk shkoi mirë në një pjesë të mirë të porosive. Askush jashtë kompanisë nuk e ka vënë re ende.',
            'Something went wrong across a good chunk of orders. Nobody outside the company has noticed yet.'),
    opts: [
      O(T('Njoftoje publikisht dhe zëvendëso', 'Announce it and replace'), T('Kosto e menjëhershme, besim afatgjatë.', 'Immediate cost, long-term trust.'),
        { cashU: -2, rep: 16, morale: 10, valuation: 1.06 },
        T('Doli lajmi për mënyrën si e trajtove. Kthehet si klientë që nuk largohen kurrë.',
          'The story became how you handled it. It comes back as customers who never leave.')),
      O(T('Rregulloje në heshtje', 'Fix it quietly'), T('Kosto e ulët, bombë me sahat.', 'Low cost, ticking clock.'),
        { cashU: -0.4, stress: 8 },
        T('Rregullohet pa zhurmë. Për momentin.', 'It gets fixed without noise. For now.'),
        { risk: { p: 0.4,
          bad: { fx: { rep: -22, revMult: 0.88, stress: 12 }, res: T('Dikush nga brenda flet. Lajmi del jashtë me fjalën "fshehje".', 'Someone inside talks. The story breaks with the word "cover-up" in it.') },
          good: { fx: { cashU: 0.2 }, res: T('Askush s\'e mori vesh. Ti e di. Kjo mjafton për sonte.', 'Nobody found out. You know. That is enough for tonight.') } } }),
      O(T('Fajëso furnitorin', 'Blame the supplier'), T('Shpëton buxhetin, humbet zinxhirin.', 'Saves the budget, breaks the chain.'),
        { rep: -6, cashU: 0.3, marginAdd: -0.03, morale: -8 },
        T('Furnitori nuk të beson më dhe kushtet përkeqësohen. Fitove tremujorin, humbe partnerin.',
          'The supplier stops trusting you and the terms get worse. You won the quarter, lost the partner.')),
    ],
  },
  {
    id: 'leverage', stage: [2, 10], weight: 6,
    req: (s) => s.revenue > 200000 && s.rep > 35,
    title: T('Levë financiare', 'Leverage'),
    body: T('Banka të ofron kapital të lirë për zgjerim. Borxhi shumëzon gjithçka — fitimin dhe gabimin njëlloj.',
            'The bank offers cheap capital for expansion. Debt multiplies everything — profit and error alike.'),
    opts: [
      O(T('Merr borxh të rëndë', 'Take heavy debt'), T('Rritje e përshpejtuar, mbijetesë e brishtë.', 'Accelerated growth, fragile survival.'),
        { debtU: 8, cashU: 8, revMult: 1.3, stress: 14, set: { levered: true } },
        T('Rritesh dyfish më shpejt. Në krizën e ardhshme, edhe bie dyfish më shpejt.',
          'You grow twice as fast. In the next crisis, you fall twice as fast too.')),
      O(T('Borxh i matur', 'Measured debt'), T('Ekuilibër i mërzitshëm dhe i mençur.', 'A boring, wise balance.'),
        { debtU: 3, cashU: 3, revMult: 1.12 },
        T('Sa duhet, jo sa mundesh. Bankierët zhgënjehen lehtë.',
          'As much as needed, not as much as possible. Bankers are easily disappointed.')),
      O(T('Shlyej borxhin ekzistues', 'Pay down existing debt'), T('Fle natën. Rritesh ngadalë.', 'You sleep at night. You grow slowly.'),
        { cashU: -3, debtClear: 0.6, stress: -12, rep: 5 },
        T('Bilanci bëhet i pastër. Në krizë, kjo do të jetë arma jote më e mirë.',
          'The balance sheet gets clean. In a crisis, that will be your best weapon.')),
    ],
  },
  {
    id: 'systems', stage: [2, 10], once: true, weight: 6,
    req: (s) => s.teamSize >= 8,
    title: T('Sistemet', 'Systems'),
    body: T('Kompania funksionon sepse njerëzit mbajnë mend gjëra. Kjo nuk shkallëzohet.',
            'The company works because people remember things. That does not scale.'),
    opts: [
      O(T('Investim i madh në procese', 'Invest heavily in process'), T('Ngadalëson sot, shumëzon nesër.', 'Slows today, multiplies tomorrow.'),
        { cashU: -2.5, marginAdd: 0.08, revMult: 0.97, valuation: 1.18, morale: -4, set: { systemized: true } },
        T('Gjashtë muaj ankesa. Pastaj kompania nis të punojë edhe kur ti je me pushime.',
          'Six months of complaints. Then the company starts working even while you are on holiday.')),
      O(T('Automatizo pjesët e lodhshme', 'Automate the boring parts'), T('Kosto më e ulët, ekip më i vogël.', 'Lower cost, smaller team.'),
        { cashU: -1.2, marginAdd: 0.05, team: -1, morale: -6 },
        T('Dy role zhduken. Njerëzit e kuptojnë se çfarë do të thotë kjo për ta.',
          'Two roles disappear. People understand what that means for them.')),
      O(T('Vazhdo me kaos', 'Stay chaotic'), T('Shpejtësi tani, mur më vonë.', 'Speed now, a wall later.'),
        { revMult: 1.05, stress: 10, marginAdd: -0.02 },
        T('Ende shpejt. Por çdo punonjës i ri kërkon dy muaj për të kuptuar si funksionon gjithçka.',
          'Still fast. But every new hire needs two months to understand how anything works.')),
    ],
  },
  {
    id: 'bad_apple', stage: [1, 10], weight: 5,
    req: (s) => s.teamSize >= 6,
    title: T('Ylli toksik', 'The toxic star'),
    body: T('Personi yt më produktiv po shkatërron moralin e gjithë ekipit. Numrat janë të pamohueshëm.',
            'Your most productive employee is destroying the morale of everyone else. Their numbers are undeniable.'),
    opts: [
      O(T('Largoje menjëherë', 'Fire them now'), T('Humbje e menjëhershme, ajër i pastër.', 'Immediate loss, clean air.'),
        { revMult: 0.93, morale: 20, rep: 6 },
        T('Të nesërmen ekipi punon ndryshe. Dikush të thotë faleminderit në korridor.',
          'The next day the team works differently. Someone thanks you in the corridor.')),
      O(T('Mbaje për numrat', 'Keep them for the numbers'), T('Rezultate sot, ekip i thyer nesër.', 'Results today, broken team tomorrow.'),
        { revMult: 1.06, morale: -18, rep: -4 },
        T('Numrat mbahen. Dy nga njerëzit e tu më të mirë nisin të kërkojnë punë tjetër.',
          'The numbers hold. Two of your best people quietly start job hunting.')),
      O(T('Konfrontim dhe kufij', 'Confront and set limits'), T('Zgjidhje e vështirë, rezultat i pasigurt.', 'Hard path, uncertain result.'),
        { stress: 8 },
        T('E ul në tavolinë dhe i thua gjithçka drejtpërdrejt.', 'You sit them down and say all of it directly.'),
        { risk: { p: 0.45,
          bad: { fx: { revMult: 0.9, morale: -6 }, res: T('Largohet i ofenduar dhe merr dy klientë me vete.', 'They leave offended and take two clients with them.') },
          good: { fx: { morale: 14, revMult: 1.03, rep: 5 }, res: T('Ndryshon vërtet. Rrallë ndodh — por ndodhi.', 'They change. It rarely happens — but it happened.') } } }),
    ],
  },
  {
    id: 'tax_scheme', stage: [2, 11], once: true, weight: 5,
    req: (s) => s.revenue > 400000,
    title: T('Struktura e zgjuar', 'The clever structure'),
    body: T('Një konsulent të tregon një strukturë që ul taksat në mënyrë dramatike. Ligjore. Në letër.',
            'A consultant shows you a structure that slashes your tax bill. Legal. On paper.'),
    opts: [
      O(T('Zbatoje', 'Implement it'), T('Para të shumta, ekspozim publik.', 'Serious money, public exposure.'),
        { marginAdd: 0.08, cashU: 2, influence: 4 },
        T('Fitimi neto kërcen ndjeshëm. Dosja ekziston diku.', 'Net profit jumps sharply. The file exists somewhere.'),
        { risk: { p: 0.33,
          bad: { fx: { rep: -26, cashU: -4, stress: 16, marginAdd: -0.08 }, res: T('Një gazetar e gjen strukturën. Titulli të ndjek për vite.', 'A journalist finds the structure. The headline follows you for years.') },
          good: { fx: { cashU: 1.5 }, res: T('Askush nuk pyeti. Paratë mbetën në llogari.', 'Nobody asked. The money stayed in the account.') } } }),
      O(T('Vetëm optimizimi i thjeshtë', 'Simple optimisation only'), T('Fitim modest, gjumë i qetë.', 'Modest gain, quiet sleep.'),
        { marginAdd: 0.02, rep: 4 },
        T('Bën atë që bën çdo kompani serioze dhe asgjë më shumë.',
          'You do what every serious company does and nothing more.')),
      O(T('Paguaj gjithçka dhe trumbetoje', 'Pay in full and say so publicly'), T('Kosto reale, kapital reputacioni.', 'Real cost, reputational capital.'),
        { marginAdd: -0.02, rep: 14, influence: 8 },
        T('Bëhesh shembulli që citohet. Kjo hap dyer politike që paratë nuk i hapin.',
          'You become the example people cite. That opens political doors money cannot.')),
    ],
  },
  {
    id: 'corporate_partner', stage: [3, 10], weight: 5,
    req: (s) => s.revenue > 600000,
    title: T('Gjiganti troket', 'The giant knocks'),
    body: T('Një korporatë e madhe do të integrojë produktin tënd. Kontrata është e shkëlqyer dhe të lidh duart.',
            'A large corporation wants to integrate your product. The contract is excellent and it ties your hands.'),
    opts: [
      O(T('Nënshkruaj marrëveshjen e madhe', 'Sign the big one'), T('Rritje e fortë, varësi strategjike.', 'Strong growth, strategic dependency.'),
        { revU: 3, marginAdd: -0.05, influence: 12, valuation: 1.12, set: { dependent: true } },
        T('Të ardhurat trefishohen nga një burim i vetëm. Fuqia negociuese kalon tek ata.',
          'Revenue triples from a single source. The negotiating power moves to them.')),
      O(T('Negocio ashpër', 'Negotiate hard'), T('Rrezikon marrëveshjen për kushte më të mira.', 'Risks the deal for better terms.'),
        { stress: 8 },
        T('Ti kërkon më shumë se sa presin.', 'You ask for more than they expect.'),
        { risk: { p: 0.42,
          bad: { fx: { rep: -4, influence: -4 }, res: T('Ata largohen nga tavolina. Ti mbetesh me krenarinë dhe pa kontratë.', 'They walk from the table. You keep your pride and no contract.') },
          good: { fx: { revU: 2.6, marginAdd: 0.02, rep: 10, influence: 10 }, res: T('Ata pranojnë. Nga sot të trajtojnë si të barabartë.', 'They accept. From today they treat you as an equal.') } } }),
      O(T('Refuzo dhe konkurro', 'Refuse and compete'), T('Rrugë e vështirë, kompani e pavarur.', 'Hard road, independent company.'),
        { rep: 8, morale: 10, stress: 10, revMult: 1.03 },
        T('Ekipi u ngrit në këmbë kur e dëgjoi. Tani duhet të provoni se kishit të drejtë.',
          'The team stood up when they heard. Now you have to prove you were right.')),
    ],
  },
  {
    id: 'lawsuit', stage: [2, 11], weight: 5,
    req: (s) => s.revenue > 300000,
    title: T('Padia', 'The lawsuit'),
    body: T('Dikush të padit. Nuk ka rëndësi nëse ke të drejtë — ka rëndësi sa gjatë mund të paguash avokatët.',
            'Someone is suing you. Being right does not matter — how long you can pay lawyers does.'),
    opts: [
      O(T('Lufto deri në fund', 'Fight it to the end'), T('E shtrenjtë, parimore.', 'Expensive, principled.'),
        { cashU: -2.5, stress: 14 },
        T('Hyn në gjyq me bindjen se ke të drejtë.', 'You go to court convinced you are right.'),
        { risk: { p: 0.4,
          bad: { fx: { cashU: -3, rep: -12 }, res: T('Humbet. Paguan dëmin dhe shpenzimet e palës tjetër.', 'You lose. You pay damages and their costs too.') },
          good: { fx: { rep: 14, influence: 8 }, res: T('Fiton. Tregu mëson se ti nuk paguan për të heshtur.', 'You win. The market learns you do not pay to make things go away.') } } }),
      O(T('Marrëveshje jashtë gjykatës', 'Settle quietly'), T('Kosto e sigurt, pa titull gazete.', 'Certain cost, no headlines.'),
        { cashU: -1.6, rep: -3, stress: -6 },
        T('Paguan dhe mbaron. Është zgjidhja e mërzitshme dhe zakonisht e saktë.',
          'You pay and it ends. The boring answer, and usually the right one.')),
    ],
  },
  {
    id: 'mentor', stage: [1, 8], once: true, weight: 5,
    title: T('Mentori', 'The mentor'),
    body: T('Dikush që e ka ndërtuar dhe humbur një perandori të ofron kohën e vet. Në këmbim kërkon sinqeritet total.',
            'Someone who built and lost an empire offers you their time. In exchange they want total honesty.'),
    opts: [
      O(T('Prano dhe dëgjo', 'Accept and listen'), T('Gabime më pak, ego më e vogël.', 'Fewer mistakes, smaller ego.'),
        { influence: 10, rep: 6, stress: -10, revMult: 1.06,
          join: { mentor: { loyalty: 70 } }, set: { hasMentor: true } },
        T('Të thotë tri gjëra që nuk doje t\'i dëgjoje. Të treja rezultojnë të vërteta.',
          'They tell you three things you did not want to hear. All three turn out true.'),
        { queue: [{ id: 'arc_mentor_call', in: 9 }] }),
      O(T('Prano dhe jepi 2%', 'Accept and give 2%'), T('Angazhim i vërtetë nga ana e vet.', 'Real skin in the game for them.'),
        { equity: -2, influence: 16, revMult: 1.1, valuation: 1.08,
          join: { mentor: { loyalty: 85 } }, set: { hasMentor: true } },
        T('Tani merr telefon për ty edhe pa ia kërkuar. Rrjeti që ka ndërtuar bëhet i yti.',
          'Now they make calls for you unasked. Their network becomes yours.'),
        { queue: [{ id: 'arc_mentor_call', in: 7 }] }),
      O(T('Nuk kam kohë', 'No time for that'), T('Vazhdon vetëm.', 'You carry on alone.'),
        { stress: 4, influence: -2 },
        T('Mëson gjithçka vetë, ngadalë dhe shtrenjtë.',
          'You learn everything yourself, slowly and expensively.')),
    ],
  },
  {
    id: 'second_line', stage: [2, 10], weight: 6,
    req: (s) => s.revenue > 400000,
    title: T('Linja e dytë', 'The second line'),
    body: T('Një produkt i vetëm është një pikë dështimi e vetme. Por fokusi është arsyeja pse ke arritur deri këtu.',
            'A single product is a single point of failure. But focus is the reason you got this far.'),
    opts: [
      O(T('Nis linjën e dytë', 'Launch a second line'), T('Diversifikim, vëmendje e ndarë.', 'Diversification, split attention.'),
        { cashU: -2, revU: 1.6, stress: 8, marginAdd: -0.02 },
        T('Dy biznese nën një çati. Të dyja kërkojnë drejtuesin më të mirë që ke.',
          'Two businesses under one roof. Both want the best operator you have.')),
      O(T('Thellohu në një gjë', 'Go deeper on one thing'), T('Dominim i ngushtë.', 'Narrow dominance.'),
        { marginAdd: 0.07, revMult: 1.1, rep: 8, valuation: 1.1 },
        T('Bëhesh emri i parë që përmendet në kategorinë tënde. Kjo vlen më shumë se një linjë e dytë mediokre.',
          'You become the first name mentioned in your category. Worth more than a mediocre second line.')),
      O(T('Blej një konkurrent të vogël', 'Buy a small competitor'), T('Rritje e blerë, integrim i dhimbshëm.', 'Bought growth, painful integration.'),
        { cashU: -4, revU: 2.2, team: 4, morale: -8, influence: 6 },
        T('Marrja e kompanisë zgjat një javë. Bashkimi i dy kulturave zgjat dy vjet.',
          'Buying the company takes a week. Merging two cultures takes two years.')),
    ],
  },
];

export default MID;
