// ======================================================= ACT III — THE EMPIRE
// Plus the industry-specific scenes that only one kind of career ever sees.

const T = (sq, en) => ({ sq, en });
const O = (label, hint, fx, res, extra = {}) => ({ label, hint, fx, res, ...extra });

const LATE = [
  {
    id: 'ipo', stage: [5, 12], once: true, weight: 8,
    req: (s) => s.revenue > 8000000 && s.rep > 45,
    title: T('Bursa', 'The public markets'),
    body: T('Bankierët thonë se je gati. Dalja në bursë do të thotë kapital pa fund dhe një audiencë që të gjykon çdo tremujor.',
            'The bankers say you are ready. Going public means endless capital and an audience that judges you every quarter.'),
    opts: [
      O(T('Dil në bursë', 'Go public'), T('Likuiditet masiv, liri e humbur.', 'Massive liquidity, freedom lost.'),
        { cashU: 14, equity: -25, valuation: 1.5, influence: 25, rep: 14, stress: 14, multipleAdd: 2, set: { public: true } },
        T('Zilja bie dhe numri në ekran bëhet publik. Ti nuk je më pronar — je menaxher i pritshmërive.',
          'The bell rings and the number on the screen becomes public. You are no longer an owner — you manage expectations.')),
      O(T('Mbetu privat', 'Stay private'), T('Më pak para, shumë më shumë kontroll.', 'Less money, far more control.'),
        { rep: 8, morale: 8, stress: -8, valuation: 1.05 },
        T('U thua jo dhe gazetat shkruajnë për të. Ekipi yt e lexon me krenari.',
          'You say no and the press writes about it. Your team reads it with pride.')),
      O(T('Shit shumicën e aksioneve', 'Sell the majority'), T('Dalje me para në dorë. Fund i një kapitulli.', 'Cash out. The end of a chapter.'),
        { cashU: 20, equity: -55, influence: 10, stress: -25 },
        T('Nënshkrimi zgjat dhjetë sekonda. Pas tij, kompania vazhdon pa ty në timon.',
          'The signature takes ten seconds. After it, the company carries on without you at the wheel.')),
    ],
  },
  {
    id: 'acquire_rival', stage: [5, 12], weight: 7,
    req: (s) => s.rivals.some((r) => r.alive) && s.cash > 0,
    title: T('Blerja e rivalit', 'Buying the rival'),
    body: T('Një nga konkurrentët e tu është i lodhur dhe i hapur ndaj ofertave. Blerja e tij të jep treg — dhe problemet e tij.',
            'One of your competitors is tired and open to offers. Buying them gives you market — and their problems.'),
    opts: [
      O(T('Blej me para në dorë', 'Buy with cash'), T('E shtrenjtë, e pastër.', 'Expensive, clean.'),
        { cashU: -9, revU: 3.2, team: 8, influence: 12, morale: -6, set: { acquirer: true } },
        T('Nënshkruani në një sallë të ftohtë. Emri i tyre zhduket nga tregu brenda gjashtë muajsh.',
          'You sign in a cold room. Their name disappears from the market within six months.')),
      O(T('Blej me aksione', 'Buy with stock'), T('Ruan cash-in, holl pronësinë.', 'Preserves cash, dilutes you.'),
        { equity: -12, revU: 3.4, team: 8, valuation: 1.1, influence: 10 },
        T('Nuk preke llogarinë. Por tani ish-rivali yt ulet në bordin tënd.',
          'You did not touch the bank account. But your former rival now sits on your board.')),
      O(T('Lëri të shemben vetë', 'Let them collapse'), T('Durim. Rrezik se dikush tjetër i blen.', 'Patience. Risk that someone else buys them.'),
        { cashU: 0.5, stress: -4 },
        T('Ti pret. Në këtë lojë durimi është gjithashtu strategji.',
          'You wait. In this game patience is also a strategy.')),
    ],
  },
  {
    id: 'diversify', stage: [6, 12], weight: 6,
    req: (s) => s.cash > 0 && s.revenue > 20000000,
    title: T('Perandoria me shumë krerë', 'The many-headed empire'),
    body: T('Ke para që nuk punojnë. Mund të ndërtosh një grup që prek disa industri — ose të mbetesh mjeshtër i një zanati.',
            'You have money that is not working. You can build a group that touches several industries — or stay master of one craft.'),
    opts: [
      O(T('Ndërto holdingun', 'Build the holding group'), T('Stabilitet nëpër cikle, fokus i holluar.', 'Stability across cycles, diluted focus.'),
        { cashU: -8, revU: 2.4, multipleAdd: -0.5, influence: 18, valuation: 1.1, set: { holding: true } },
        T('Tani kur një sektor bie, një tjetër të mban. Asnjëri nuk të njeh si më të mirin.',
          'When one sector falls, another holds you up. None of them knows you as the best.')),
      O(T('Blej pasuri të paluajtshme', 'Buy real assets'), T('Mburojë ndaj krizave, rritje e ngadaltë.', 'Crisis armour, slow growth.'),
        { cashU: -6, fixedCostU: -0.8, rep: 6, set: { assetsHedge: true } },
        T('Ndërtesat nuk rriten shpejt. Por as nuk zhduken kur tregu çmendet.',
          'Buildings do not grow fast. They also do not vanish when the market loses its mind.')),
      O(T('Rishpërndaj gjithçka në biznesin bazë', 'Reinvest all into the core'), T('Bast total mbi vetveten.', 'A total bet on yourself.'),
        { cashU: -7, revMult: 1.3, valuation: 1.15, stress: 8 },
        T('Vendos gjithçka aty ku e njeh lojën më mirë se kushdo. Nëse gabon, gabon i madh.',
          'You put everything where you know the game better than anyone. If you are wrong, you are wrong big.')),
    ],
  },
  {
    id: 'lobby', stage: [6, 12], once: true, weight: 5,
    req: (s) => s.influence > 40,
    title: T('Korridoret e pushtetit', 'The corridors of power'),
    body: T('Një rregullore e re mund ta ndryshojë industrinë tënde. Ti ke tani mjaft ndikim sa të ndikosh mbi të.',
            'A new regulation could reshape your industry. You now have enough influence to shape it.'),
    opts: [
      O(T('Lobo agresivisht', 'Lobby aggressively'), T('Avantazh strukturor, ekspozim etik.', 'Structural advantage, ethical exposure.'),
        { cashU: -3, influence: 18 },
        T('Takimet bëhen pa dëshmitarë.', 'The meetings happen without witnesses.'),
        { risk: { p: 0.35,
          bad: { fx: { rep: -24, stress: 14, cashU: -2 }, res: T('Emri yt del në një hetim. Gjithçka e ndërtuar tingëllon papritur e ndotur.', 'Your name surfaces in an inquiry. Everything you built suddenly sounds dirty.') },
          good: { fx: { marginAdd: 0.07, revMult: 1.18, influence: 10 }, res: T('Rregullorja del ashtu siç e kërkove. Konkurrentët zgjohen në një treg tjetër.', 'The regulation lands exactly as you asked. Competitors wake up in a different market.') } } }),
      O(T('Ndërto koalicion të hapur', 'Build an open coalition'), T('Më e ngadaltë, e qëndrueshme.', 'Slower, durable.'),
        { influence: 12, rep: 12, revMult: 1.05 },
        T('Bashkon industrinë rreth një standardi. Bëhesh zëri i saj publik.',
          'You unite the industry around a standard. You become its public voice.')),
      O(T('Rri larg politikës', 'Stay out of politics'), T('Pastërti, pa mbrojtje.', 'Clean hands, no protection.'),
        { rep: 6, stress: -6 },
        T('Rregullorja del pa ty. Përshtatesh, si gjithmonë.',
          'The regulation passes without you. You adapt, as always.')),
    ],
  },
  {
    id: 'moonshot', stage: [6, 12], weight: 6,
    req: (s) => s.cash > 0 && s.revenue > 15000000,
    title: T('Basti i madh', 'The moonshot'),
    body: T('Ekipi yt kërkimor ka diçka që mund ta ndryshojë industrinë ose të djegë një pjesë të madhe të kapitalit.',
            'Your research team has something that could redefine the industry or incinerate a large part of your capital.'),
    opts: [
      O(T('Financo plotësisht', 'Fund it fully'), T('Mundësi historike, rrezik real.', 'Historic upside, real risk.'),
        { cashU: -9, stress: 12, morale: 10 },
        T('Vendos një shumë që të dhemb mbi diçka që ende nuk ekziston.',
          'You put a painful amount of money behind something that does not exist yet.'),
        { risk: { p: 0.45,
          bad: { fx: { cashU: -2, morale: -12, rep: -6 }, res: T('Tre vjet punë mbyllen me një prezantim të heshtur. Mëson shumë. Paguan më shumë.', 'Three years of work end in a quiet presentation. You learn a lot. You pay more.') },
          good: { fx: { revMult: 1.6, valuation: 1.45, multipleAdd: 2, rep: 18, influence: 14 }, res: T('Funksionon. Industria ndahet në para dhe pas kësaj dite.', 'It works. The industry splits into before and after this day.') } } }),
      O(T('Financo me partner', 'Fund it with a partner'), T('Rrezik i ndarë, fitim i ndarë.', 'Shared risk, shared reward.'),
        { cashU: -3.5, equity: -5, valuation: 1.12, revMult: 1.12 },
        T('Dikush tjetër mban gjysmën e rrezikut — dhe gjysmën e lavdisë.',
          'Someone else carries half the risk — and half the glory.')),
      O(T('Mbylle projektin', 'Kill the project'), T('Disiplinë. Ndoshta edhe frikë.', 'Discipline. Possibly fear.'),
        { cashU: 1.5, morale: -10, marginAdd: 0.03 },
        T('Numrat duken më mirë menjëherë. Dy nga studiuesit e tu japin dorëheqjen brenda muajit.',
          'The numbers improve immediately. Two of your researchers resign within the month.')),
    ],
  },
  {
    id: 'succession', stage: [7, 12], once: true, weight: 5,
    req: (s) => s.year > 12,
    title: T('Pasardhësi', 'Succession'),
    body: T('Je në kulm dhe i lodhur. Pyetja nuk është nëse do të dorëzosh timonin, por kujt dhe kur.',
            'You are at the top and tired. The question is not whether you hand over the wheel, but to whom and when.'),
    opts: [
      O(T('Emëro një drejtues dhe rri në bord', 'Appoint a CEO, keep the board seat'), T('Liri pa humbur pronësinë.', 'Freedom without losing ownership.'),
        { stress: -30, revMult: 1.06, morale: 8, influence: 6, set: { steppedBack: true } },
        T('E shikon kompaninë të ecë pa ty. Dhemb dhe çliron njëkohësisht.',
          'You watch the company move without you. It hurts and frees you at the same time.')),
      O(T('Vazhdo ti, si gjithmonë', 'Keep running it yourself'), T('Kontroll total, trup i lodhur.', 'Total control, tired body.'),
        { stress: 16, revMult: 1.08, rep: 4 },
        T('Askush nuk e drejton këtë kompani si ti. Kjo është edhe e vërtetë, edhe problemi.',
          'Nobody runs this company like you do. That is both true and the problem.')),
      O(T('Tërhiqu plotësisht', 'Retire completely'), T('Fund i zgjedhur nga ti.', 'An ending you chose.'),
        { }, T('Mbyll derën nga jashtë, për herë të parë pa çelësa.', 'You close the door from outside, keyless for the first time.'),
        { end: 'retired' }),
    ],
  },
  {
    id: 'philanthropy', stage: [7, 12], once: true, weight: 5,
    title: T('Çfarë mbetet pas teje', 'What outlives you'),
    body: T('Paratë janë bërë abstrakte. Tani pyetja është se çfarë emri lë pas kur numrat nuk kanë më rëndësi.',
            'The money has become abstract. Now the question is what name you leave when the numbers stop mattering.'),
    opts: [
      O(T('Themelo një fondacion', 'Start a foundation'), T('Kapital jashtë, reputacion brenda.', 'Capital out, reputation in.'),
        { cashU: -6, rep: 22, influence: 16, stress: -10 },
        T('Emri yt shkon mbi ndërtesa që nuk prodhojnë asgjë. Është investimi i parë që nuk e mat në përqindje.',
          'Your name goes on buildings that produce nothing. The first investment you do not measure in percentages.')),
      O(T('Investo te njerëzit e tu', 'Invest in your own people'), T('Kompani më e fortë, zhurmë më e vogël.', 'Stronger company, less noise.'),
        { cashU: -3, morale: 25, revMult: 1.08, rep: 8 },
        T('Pagat, aksionet, shkollimi. Ekipi mëson se besnikëria shkon në të dy drejtimet.',
          'Salaries, equity, education. The team learns that loyalty runs both ways.')),
      O(T('Asgjë. Ende jo.', 'Nothing. Not yet.'), T('Gjithçka mbetet kapital pune.', 'Everything stays working capital.'),
        { cashU: 1, rep: -6 },
        T('Paratë mbeten në lojë. Disa e quajnë disiplinë, disa mungesë imagjinate.',
          'The money stays in play. Some call it discipline, some a failure of imagination.')),
    ],
  },
];

// --------------------------------------------------------- industry specific

const INDUSTRY_CARDS = [
  {
    id: 'tech_scale', stage: [2, 10], industry: 'tech', weight: 7,
    title: T('Borxhi teknik', 'Technical debt'),
    body: T('Kodi që të çoi deri këtu nuk të çon më tutje. Rishkrimi ndal gjithçka për muaj.',
            'The code that got you here will not take you further. A rewrite stops everything for months.'),
    opts: [
      O(T('Rishkruaj nga e para', 'Rewrite from scratch'), T('Dhimbje tani, shpejtësi më vonë.', 'Pain now, speed later.'),
        { revMult: 0.92, cashU: -1.8, marginAdd: 0.08, valuation: 1.12, stress: 10 },
        T('Gjashtë muaj pa veçori të reja. Pas tyre, ekipi lëviz dy herë më shpejt.',
          'Six months without new features. After them, the team moves twice as fast.')),
      O(T('Rregullo në ecje', 'Fix it while running'), T('Kompromis i vazhdueshëm.', 'Permanent compromise.'),
        { marginAdd: 0.02, stress: 6, morale: -4 },
        T('Ecën përpara duke rregulluar poshtë vetes. Funksionon, me kosto të fshehur.',
          'You move forward while patching underneath. It works, at a hidden cost.')),
      O(T('Injoroje', 'Ignore it'), T('Shpejtësi sot, mur nesër.', 'Speed today, a wall tomorrow.'),
        { revMult: 1.06, marginAdd: -0.04 },
        T('Vazhdon shpejt. Deri në ditën kur një ndryshim i vogël rrëzon gjithë sistemin.',
          'You keep sprinting. Until the day a small change takes the whole system down.')),
    ],
  },
  {
    id: 'tech_ai', stage: [3, 12], industry: 'tech', once: true, weight: 7,
    title: T('Vala e re', 'The new wave'),
    body: T('Një teknologji e re po ribën industrinë tënde. Mund ta përqafosh, ta injorosh ose ta blesh.',
            'A new technology is rewriting your industry. You can embrace it, ignore it or buy it.'),
    opts: [
      O(T('Rindërto produktin rreth saj', 'Rebuild the product around it'), T('Bast i madh mbi të ardhmen.', 'A heavy bet on the future.'),
        { cashU: -4, revMult: 1.05, stress: 12 },
        T('Rrezikon gjithçka mbi një teknologji që askush nuk e kupton plotësisht.',
          'You stake everything on a technology nobody fully understands yet.'),
        { risk: { p: 0.35,
          bad: { fx: { revMult: 0.85, rep: -8, cashU: -1.5 }, res: T('Vala kaloi mbi ty pa të ngritur. Klientët nuk e kërkuan kurrë.', 'The wave passed over you without lifting you. Customers never asked for it.') },
          good: { fx: { revMult: 1.55, valuation: 1.4, multipleAdd: 2, rep: 14 }, res: T('Je nga të parët. Tregu të rishpik si lider të kategorisë.', 'You are among the first. The market reinvents you as the category leader.') } } }),
      O(T('Integroje ngadalë', 'Integrate gradually'), T('Përfitim i sigurt, pa lavdi.', 'Safe gain, no glory.'),
        { revMult: 1.12, marginAdd: 0.04, cashU: -1 },
        T('E fut ku ka kuptim dhe askund tjetër. Numrat përmirësohen pa drama.',
          'You put it where it makes sense and nowhere else. The numbers improve without drama.')),
    ],
  },
  {
    id: 'food_chain', stage: [2, 10], industry: 'food', weight: 7,
    title: T('Lokali i dytë', 'The second location'),
    body: T('I pari funksionon sepse ti je aty çdo ditë. I dyti do të provojë nëse ke ndërtuar biznes apo punë.',
            'The first one works because you are there every day. The second will prove whether you built a business or a job.'),
    opts: [
      O(T('Hap tre njëherësh', 'Open three at once'), T('Shkallë e shpejtë, kontroll i humbur.', 'Fast scale, lost control.'),
        { cashU: -5, revU: 2.8, fixedCostU: 1.8, stress: 16, marginAdd: -0.04 },
        T('Tre çelësa në xhep dhe asnjë natë e qetë. Cilësia varet nga njerëz që sapo i njohe.',
          'Three sets of keys and no quiet nights. Quality now depends on people you just met.')),
      O(T('Hap një dhe përsose modelin', 'Open one and perfect the model'), T('Bazë për 20 të tjerë.', 'A base for the next twenty.'),
        { cashU: -2, revU: 1.1, fixedCostU: 0.6, marginAdd: 0.03, set: { systemized: true } },
        T('I dyti është kopje e saktë e të parit. Tani e di se modeli përsëritet.',
          'The second is an exact copy of the first. Now you know the model repeats.')),
      O(T('Shit franshizë', 'Sell franchises'), T('Rritje pa kapital, cilësi e rrezikuar.', 'Growth without capital, quality at risk.'),
        { revU: 2, marginAdd: 0.06, rep: -4, influence: 8 },
        T('Të tjerët paguajnë për të ndërtuar emrin tënd. Dhe për ta dëmtuar atë, nëse gabojnë.',
          'Others pay to build your name. And to damage it, if they get it wrong.')),
    ],
  },
  {
    id: 'food_scare', stage: [2, 12], industry: 'food', weight: 6,
    title: T('Frika ushqimore', 'The health scare'),
    body: T('Një klient postoi një ankesë për higjienën. Në industrinë tënde, kjo përhapet për orë.',
            'A customer posted a hygiene complaint. In your industry, that spreads in hours.'),
    opts: [
      O(T('Mbyll gjithçka dhe inspekto', 'Shut everything and inspect'), T('Humbje e menjëhershme, besim i ruajtur.', 'Immediate loss, trust preserved.'),
        { revMult: 0.9, cashU: -1, rep: 18, morale: 8 },
        T('Dy ditë të mbyllur dhe një raport publik. Klientët kthehen më besnikë se më parë.',
          'Two days closed and a public report. Customers come back more loyal than before.')),
      O(T('Përgjigju publikisht dhe vazhdo', 'Respond publicly and carry on'), T('Balancë e brishtë.', 'A fragile balance.'),
        { rep: 4, stress: 8, revMult: 0.97 },
        T('Shpjegon qetë dhe me fakte. Shumica e beson.', 'You explain calmly, with facts. Most people believe you.')),
      O(T('Injoroje, do të kalojë', 'Ignore it, it will pass'), T('Kursen para, rrezikon markën.', 'Saves money, risks the brand.'),
        { cashU: 0.2 },
        T('Nuk përgjigjesh. Interneti vendos vetë.', 'You do not respond. The internet decides on its own.'),
        { risk: { p: 0.5,
          bad: { fx: { rep: -26, revMult: 0.78 }, res: T('Postimi shpërthen. Rezervimet bien për javë të tëra.', 'The post explodes. Bookings collapse for weeks.') },
          good: { fx: { rep: -2 }, res: T('U harrua brenda tri ditësh.', 'It was forgotten within three days.') } } }),
    ],
  },
  {
    id: 'retail_flagship', stage: [3, 11], industry: 'retail', weight: 7,
    title: T('Dyqani-flamur', 'The flagship'),
    body: T('Një hapësirë në rrugën më të shtrenjtë të qytetit. Nuk do të nxjerrë fitim. Do të nxjerrë status.',
            'A space on the most expensive street in the city. It will not make profit. It will make status.'),
    opts: [
      O(T('Merre', 'Take it'), T('Markë e ngritur, kosto brutale.', 'Elevated brand, brutal cost.'),
        { fixedCostU: 3, rep: 20, influence: 14, valuation: 1.2, revU: 1.2 },
        T('Vitrina jote bëhet reklamë 24 orë. Qiraja të kujton çdo muaj se çfarë vendose.',
          'Your window becomes a 24-hour advert. The rent reminds you every month what you decided.')),
      O(T('Shko vetëm online', 'Go online only'), T('Marzhe më të mira, shpirt më i vogël.', 'Better margins, less soul.'),
        { marginAdd: 0.1, revMult: 1.12, rep: -4 },
        T('Numrat janë më të pastër. Marka humbet diçka që nuk matet.',
          'The numbers are cleaner. The brand loses something that does not show up in numbers.')),
      O(T('Dyqan i përkohshëm', 'Pop-up'), T('Efekt pa angazhim.', 'Impact without commitment.'),
        { cashU: -1, rep: 10, revU: 0.6, influence: 6 },
        T('Tre javë, radhë përpara derës, zero qira afatgjatë. E zgjuar.',
          'Three weeks, a queue at the door, zero long-term rent. Smart.')),
    ],
  },
  {
    id: 'retail_fast', stage: [2, 11], industry: 'retail', weight: 6,
    title: T('Prodhimi i lirë', 'Cheap production'),
    body: T('Një fabrikë jashtë vendit ul koston e prodhimit me 40%. Kushtet atje nuk i ke parë kurrë.',
            'A factory abroad cuts your production cost by 40%. You have never seen the conditions there.'),
    opts: [
      O(T('Kalo prodhimin atje', 'Move production there'), T('Marzhe të mëdha, rrezik etik.', 'Fat margins, ethical exposure.'),
        { marginAdd: 0.14, cashU: 1 },
        T('Marzhi kërcen menjëherë.', 'The margin jumps instantly.'),
        { risk: { p: 0.35,
          bad: { fx: { rep: -28, revMult: 0.85, morale: -12 }, res: T('Një reportazh tregon kushtet. Klientët e tu më besnikë ndihen të tradhtuar.', 'A report exposes the conditions. Your most loyal customers feel betrayed.') },
          good: { fx: { cashU: 1.5 }, res: T('Zinxhiri mbetet i padukshëm. Marzhi mbetet i lartë.', 'The chain stays invisible. The margin stays high.') } } }),
      O(T('Prodhim lokal, çmim premium', 'Local production, premium price'), T('Kosto e lartë, histori e fortë.', 'High cost, strong story.'),
        { marginAdd: -0.03, rep: 16, valuation: 1.12, revMult: 1.06 },
        T('Etiketa "prodhuar këtu" bëhet pjesë e produktit. Njerëzit paguajnë për të.',
          'The "made here" label becomes part of the product. People pay for it.')),
      O(T('Auditim i plotë dhe transparencë', 'Full audit and transparency'), T('Kosto mesatare, mburojë reale.', 'Middling cost, real armour.'),
        { cashU: -1.2, marginAdd: 0.06, rep: 10 },
        T('Publikon raportin e auditimit. Askush nuk mund të të godasë me atë që e ke thënë vetë.',
          'You publish the audit. Nobody can hit you with something you said first.')),
    ],
  },
  {
    id: 'fin_fund', stage: [2, 11], industry: 'finance', weight: 7,
    title: T('Fondi i parë', 'The first fund'),
    body: T('Investitorët janë gati të të besojnë kapitalin e tyre. Tarifat janë të sigurta, përgjegjësia është e përjetshme.',
            'Investors are ready to trust you with their capital. The fees are certain, the responsibility is permanent.'),
    opts: [
      O(T('Ngri fond të madh', 'Raise a large fund'), T('Tarifa të mëdha, presion i madh.', 'Big fees, big pressure.'),
        { revU: 3, stress: 16, influence: 16, rep: 6, set: { fundManager: true } },
        T('Menaxhon para që nuk janë të tuat. Çdo tremujor dikush kërkon shpjegim.',
          'You manage money that is not yours. Every quarter somebody wants an explanation.')),
      O(T('Fond i vogël, rezultate të shkëlqyera', 'Small fund, excellent returns'), T('Reputacion para madhësisë.', 'Reputation before size.'),
        { revU: 1.1, rep: 16, influence: 10, marginAdd: 0.05 },
        T('Numri i klientëve mbetet i vogël. Lista e pritjes bëhet e gjatë.',
          'The client list stays small. The waiting list gets long.')),
      O(T('Investo vetëm paratë e tua', 'Invest only your own money'), T('Liri absolute, shkallë e kufizuar.', 'Absolute freedom, limited scale.'),
        { revMult: 1.08, stress: -10, rep: 4 },
        T('Askush nuk të telefonon kur tregu bie. Vetëm ti dhe pasojat e tua.',
          'Nobody calls you when the market drops. Only you and your own consequences.')),
    ],
  },
  {
    id: 'fin_regulator', stage: [3, 12], industry: 'finance', weight: 6,
    title: T('Rregullatori', 'The regulator'),
    body: T('Një letër zyrtare kërkon shpjegime për disa transaksione. Gjithçka është në rregull. Ndoshta.',
            'An official letter asks for explanations on certain transactions. Everything is fine. Probably.'),
    opts: [
      O(T('Bashkëpunim total', 'Full cooperation'), T('Kohë dhe kosto, pa pasoja.', 'Time and cost, no fallout.'),
        { cashU: -1.5, stress: 8, rep: 8, revMult: 0.97 },
        T('Hap çdo dosje. Procesi mbyllet pa gjoba dhe me një marrëdhënie të përmirësuar.',
          'You open every file. It closes with no fines and an improved relationship.')),
      O(T('Avokatë dhe minimumi ligjor', 'Lawyers and the legal minimum'), T('Mbron fshehtësinë, provokon dyshimin.', 'Protects secrecy, invites suspicion.'),
        { cashU: -1 },
        T('U jep saktësisht atë që kërkojnë. Asgjë më shumë.', 'You give exactly what is demanded. Nothing more.'),
        { risk: { p: 0.4,
          bad: { fx: { rep: -20, cashU: -3, influence: -8 }, res: T('Hetimi zgjerohet. Gjoba dhe titujt vijnë bashkë.', 'The inquiry widens. The fine and the headlines arrive together.') },
          good: { fx: { rep: 2 }, res: T('Dosja mbyllet pa zhurmë.', 'The file closes without noise.') } } }),
    ],
  },
];

export default [...LATE, ...INDUSTRY_CARDS];
