// Decision content. Each card is a scene; each option is a bet.
// Cards are picked by stage (career level), industry, flags and requirements,
// so two careers rarely see the same sequence.

const T = (sq, en) => ({ sq, en });
const O = (label, hint, fx, res, extra = {}) => ({ label, hint, fx, res, ...extra });

// ============================================================ ACT I — ORIGIN

const EARLY = [
  {
    id: 'first_capital', stage: [0, 2], once: true, weight: 9,
    req: (s) => !s.flags.funded,
    title: T('Kapitali i parë', 'First capital'),
    body: T('Ke një ide dhe një llogari bankare që nuk të mban gjatë. Paratë duhen sot, jo vitin tjetër.',
            'You have an idea and a bank account that will not last. The money is needed today, not next year.'),
    opts: [
      O(T('Kursimet e mia', 'My own savings'), T('Kontroll total. Rrezik personal.', 'Total control. Personal risk.'),
        { cash: 7000, stress: 10, rep: 2, set: { funded: true, bootstrapped: true } },
        T('Nuk i detyrohesh askujt. Por çdo gabim tani paguhet nga xhepi yt.',
          'You owe nobody. But every mistake now comes out of your own pocket.')),
      O(T('Hua nga familja', 'Family loan'), T('Para të shpejta, presion që nuk matet në numra.', 'Fast money, pressure that does not show on a balance sheet.'),
        { cash: 16000, debtU: 1.6, stress: 14, morale: 4, set: { funded: true, familyDebt: true } },
        T('Xhaxhai nxjerr zarfin pa pyetur shumë. Tani çdo darkë familjare ka një pyetje të fshehur.',
          'Your uncle hands over the envelope without many questions. Now every family dinner has a hidden question in it.'),
        { queue: [{ id: 'arc_family_debt', in: 10 }] }),
      O(T('Kredi bankare', 'Bank loan'), T('Më shumë kapital, interes çdo tremujor.', 'More capital, interest every quarter.'),
        { cash: 34000, debtU: 4.5, rep: 3, set: { funded: true } },
        T('Nënshkruan letrat. Banka nuk beson te ëndrra jote — beson te kolaterali.',
          'You sign the papers. The bank does not believe in your dream — it believes in collateral.')),
      O(T('Investitor engjëll', 'Angel investor'), T('Kapital dhe dyer të hapura, në këmbim të pronësisë.', 'Capital and open doors, in exchange for ownership.'),
        { cash: 45000, equity: -18, influence: 8, rep: 4, set: { funded: true, hasInvestor: true } },
        T('Çeku nënshkruhet brenda njëzet minutash. Dhe që nga sot, 18% e çdo gjëje që ndërton i takon dikujt tjetër.',
          'He writes the cheque in 20 minutes. From today, 18% of everything you build is his.')),
    ],
  },
  {
    id: 'first_product', stage: [0, 2], once: true, weight: 10,
    req: (s) => s.flags.funded && !s.flags.launched,
    title: T('Çfarë del në treg', 'What ships'),
    body: T('Produkti është gati sa për të turpëruar ose sa për të vonuar. Tregu nuk pret të përsosurën, por nuk fal as të shëmtuarën.',
            'The product is either embarrassing enough to ship or perfect enough to be late. The market will not wait, but it will not forgive garbage either.'),
    opts: [
      O(T('Nxirre sot, i papërsosur', 'Ship today, rough'), T('Të ardhura të shpejta, reputacion i lënduar.', 'Fast revenue, bruised reputation.'),
        { revU: 1.1, rep: -6, stress: 6, set: { launched: true } },
        T('Klientët e parë ankohen — por paguajnë. Ke të dhëna reale në vend të supozimeve.',
          'The first customers complain — but they pay. You have real data instead of assumptions.')),
      O(T('Edhe tre muaj punë', 'Three more months'), T('Cilësi më e lartë, para që digjen.', 'Higher quality, cash burning.'),
        { revU: 0.8, rep: 8, cashU: -0.9, stress: 8, marginAdd: 0.04, set: { launched: true, craft: true } },
        T('Del me diçka që s\'ke turp ta tregosh. Llogaria u hollua, por emri nisi mirë.',
          'You launch something you are not ashamed of. The account is thinner, but the name started clean.')),
      O(T('Shit para se ta ndërtosh', 'Sell before you build'), T('Parapagesa nga klientët. Nëse dështon, të hanë të gjallë.', 'Customer prepayments. If you fail, they eat you alive.'),
        { cashU: 1.4, stress: 12, set: { launched: true, presold: true } },
        T('Katër kontrata të nënshkruara për diçka që ende nuk ekziston. Ora ka nisur të numërojë.',
          'Four signed contracts for something that does not exist yet. The clock is running.'),
        { risk: { p: 0.3,
          bad: { fx: { rep: -14, revU: 0.4, stress: 10 }, res: T('Dorëzimi vonon gjashtë javë. Dy klientë largohen dhe flasin.', 'Delivery slips six weeks. Two clients leave and they talk.') },
          good: { fx: { revU: 1.8, rep: 6 }, res: T('E dorëzon në afat. Tani ke para dhe dëshmi njëkohësisht.', 'You deliver on time. Now you have cash and proof at once.') } } }),
    ],
  },
  {
    id: 'workspace', stage: [0, 2], once: true, weight: 6,
    req: (s) => s.flags.launched,
    title: T('Ku punohet', 'Where the work happens'),
    body: T('Tavolina e kuzhinës nuk të mban më. Por qiraja është armiku më i qetë i një biznesi të ri.',
            'The kitchen table does not hold you anymore. But rent is the quietest enemy a young business has.'),
    opts: [
      O(T('Vazhdo nga shtëpia', 'Stay home'), T('Zero kosto fikse, zero energji ekipi.', 'Zero fixed cost, zero team energy.'),
        { morale: -6, stress: 5, cashU: 0.2 },
        T('Kursen çdo euro. Por kufiri mes punës dhe jetës u zhduk plotësisht.',
          'You save every euro. But the line between work and life vanished completely.')),
      O(T('Zyrë e vogël', 'Small office'), T('Kosto fikse mujore, ekip që ndihet real.', 'Monthly fixed cost, a team that feels real.'),
        { fixedCostU: 0.9, morale: 10, rep: 4 },
        T('Njerëzit vijnë në një vend që ekziston. Diçka ndryshon në mënyrën si punojnë.',
          'People come to a place that exists. Something changes in how they work.')),
      O(T('Adresë prestigjioze', 'Prestige address'), T('Sinjal i fortë tregu, kosto e rëndë.', 'Strong market signal, heavy cost.'),
        { fixedCostU: 2.4, rep: 12, influence: 8, morale: 8 },
        T('Klientët e mëdhenj marrin takim vetëm sepse adresa tingëllon seriozisht. Kushton sa dy punonjës.',
          'Big clients take the meeting purely because the address sounds serious. It costs as much as two employees.')),
    ],
  },
  {
    id: 'first_client', stage: [0, 3], once: true, weight: 8,
    req: (s) => s.flags.launched,
    title: T('Klienti i madh', 'The whale'),
    body: T('Një klient i vetëm të ofron sa gjysma e të ardhurave të tua vjetore. Kërkon ekskluzivitet dhe afate që të thyejnë.',
            'A single client offers you half your annual revenue. They want exclusivity and deadlines that will break you.'),
    opts: [
      O(T('Prano gjithçka', 'Take the deal'), T('Rritje e menjëhershme, varësi e rrezikshme.', 'Instant growth, dangerous dependency.'),
        { revU: 2.2, stress: 14, morale: -6, set: { whale: true } },
        T('Numrat kërcejnë. Tani një telefonatë e vetme mund ta shembë gjithçka.',
          'The numbers jump. Now one phone call could bring it all down.')),
      O(T('Prano pa ekskluzivitet', 'Take it, no exclusivity'), T('Më pak para, më shumë liri.', 'Less money, more freedom.'),
        { revU: 1.2, rep: 6, influence: 4 },
        T('Ata mërmëritin, por nënshkruajnë. Ti mban të drejtën të rritesh diku tjetër.',
          'They grumble, but they sign. You keep the right to grow elsewhere.')),
      O(T('Refuzo', 'Walk away'), T('Ruan kontrollin, humbet vrullin.', 'Keeps control, loses momentum.'),
        { rep: 4, stress: -6, morale: 4 },
        T('Thua jo dhe fle mirë. Në treg përhapet se ti nuk je i uritur — dhe kjo ka vlerë.',
          'You say no and sleep well. Word spreads that you are not desperate — and that has value.')),
    ],
  },
  {
    id: 'pricing', stage: [0, 4], once: true, weight: 7,
    req: (s) => s.revenue > 0,
    title: T('Çmimi', 'The price'),
    body: T('Çmimi nuk është numër, është deklaratë. Ai vendos se kush të blen dhe kush të tregon për ty.',
            'Price is not a number, it is a statement. It decides who buys you and who talks about you.'),
    opts: [
      O(T('Premium, 40% mbi treg', 'Premium, 40% above market'), T('Marzhe të larta, treg i ngushtë.', 'High margins, narrow market.'),
        { marginAdd: 0.12, revMult: 0.88, rep: 8, valuation: 1.08 },
        T('Humb klientët e lirë dhe fiton ata që nuk pyesin për zbritje.',
          'You lose the cheap customers and win the ones who never ask for a discount.')),
      O(T('Volum, nën tregun', 'Volume, below market'), T('Rritje e shpejtë, marzhe të holla.', 'Fast growth, thin margins.'),
        { marginAdd: -0.09, revMult: 1.35, rep: -2, morale: -3 },
        T('Vëllimi shpërthen. Çdo njësi fiton pak — dhe çdo gabim kushton shumë.',
          'Volume explodes. Every unit earns little — and every mistake costs a lot.')),
      O(T('Modelim me abonim', 'Move to subscription'), T('Të ardhura të parashikueshme, hyrje më e ngadaltë.', 'Predictable revenue, slower start.'),
        { revMult: 0.92, marginAdd: 0.05, multipleAdd: 1.5, valuation: 1.12, set: { recurring: true } },
        T('Muaji i parë duket më i keq. Muaji i dymbëdhjetë duket krejt ndryshe.',
          'Month one looks worse. Month twelve looks like a different company.')),
    ],
  },
  {
    id: 'cofounder', stage: [0, 3], once: true, weight: 7,
    req: (s) => !s.flags.hasCofounder,
    title: T('Bashkëthemeluesi', 'The co-founder'),
    body: T('Dikush shumë i mirë të propozon të hyjë përkrah teje. Kërkon një pjesë të kompanisë dhe një zë në çdo vendim.',
            'Someone genuinely good offers to stand beside you. They want a slice of the company and a voice in every decision.'),
    opts: [
      O(T('Jepi 30%', 'Give them 30%'), T('Partner i vërtetë, pronësi e ndarë.', 'A real partner, shared ownership.'),
        { equity: -30, revMult: 1.2, morale: 12, stress: -12, rep: 6,
          join: { cofounder: { loyalty: 82 } }, set: { hasCofounder: true } },
        T('Papritur nuk je vetëm në orën tre të natës. Vlen më shumë se sa duket në tabelë.',
          'Suddenly you are not alone at three in the morning. It is worth more than the cap table shows.'),
        { queue: [{ id: 'arc_cof_tension', in: 8 }] }),
      O(T('Jepi 8% dhe titull', 'Give 8% and a title'), T('Ruan kontrollin, rrezikon besnikërinë.', 'Keeps control, risks loyalty.'),
        { equity: -8, revMult: 1.08, morale: 4,
          join: { cofounder: { loyalty: 46 } }, set: { hasCofounder: true, thinDeal: true } },
        T('Pranon me buzëqeshje të ngrirë. Ti e di që ky numër nuk harrohet kurrë.',
          'They accept with a frozen smile. You know they will remember that number.'),
        { queue: [{ id: 'arc_cof_tension', in: 6 }] }),
      O(T('Vazhdo vetëm', 'Go it alone'), T('100% e jotja, 100% barra.', '100% yours, 100% the weight.'),
        { stress: 12, rep: 2, influence: -4 },
        T('Askush nuk ta merr pjesën. Askush nuk ta merr as barrën.',
          'Nobody takes your share. Nobody takes the weight either.')),
    ],
  },
  {
    id: 'first_hire', stage: [0, 4], once: true, weight: 8,
    req: (s) => s.revenue > 0 && s.teamSize < 4,
    title: T('Punësimi i parë', 'The first hire'),
    body: T('Tre kandidatë, një pagë. Kush hyn i pari përcakton kulturën e çdo personi që vjen pas tij.',
            'Three candidates, one salary. Whoever comes first defines the culture of everyone who follows.'),
    opts: [
      O(T('Veterani i shtrenjtë', 'The expensive veteran'), T('Rezultat i menjëhershëm, kosto e rëndë.', 'Immediate output, heavy cost.'),
        { team: 1, costMult: 1.12, revU: 0.9, rep: 5, stress: -5 },
        T('E ka bërë këtë tri herë më parë. Paga që kërkon të dhemb, gabimet e shmangura jo.',
          'They have done this three times before. The salary hurts, the avoided mistakes do not.')),
      O(T('I riu i uritur', 'The hungry junior'), T('I lirë, i papërvojë, besnik.', 'Cheap, raw, loyal.'),
        { team: 1, revU: 0.35, morale: 8, stress: 4 },
        T('Nuk di shumë, por mëson çdo ditë dhe nuk largohet kurrë para teje.',
          'They know little, but learn daily and never leave before you do.')),
      O(T('Askush ende', 'Nobody yet'), T('Kursen para, paguan me trupin tënd.', 'Saves cash, paid in your own body.'),
        { cashU: 0.4, stress: 10, morale: -4 },
        T('E bën vetë. Përsëri. Dhe javët nisin të ngjajnë me njëra-tjetrën.',
          'You do it yourself. Again. And the weeks start to look identical.')),
    ],
  },
  {
    id: 'legal_setup', stage: [0, 3], once: true, weight: 6,
    title: T('Letrat', 'The paperwork'),
    body: T('Kontratat, taksat, licencat. E mërzitshme derisa bëhet e vetmja gjë që ka rëndësi.',
            'Contracts, taxes, licences. Boring until it becomes the only thing that matters.'),
    opts: [
      O(T('Avokat i mirë, kosto e lartë', 'Proper lawyer, real cost'), T('Mbrojtje afatgjatë.', 'Long-term protection.'),
        { cashU: -1.1, rep: 5, set: { cleanLegal: true } },
        T('Çdo gjë e regjistruar si duhet. Ke fjetur mbrëmjen e parë pa menduar për gjyqe.',
          'Everything filed properly. You sleep your first evening without thinking about lawsuits.')),
      O(T('Model nga interneti', 'Template off the internet'), T('Falas. Deri në ditën që nuk është.', 'Free. Until the day it is not.'),
        { cashU: 0.15, stress: 4 },
        T('Funksionon. Për momentin.', 'It works. For now.'),
        { risk: { p: 0.35,
          bad: { fx: { rep: -12, cashU: -1.4, stress: 12 }, res: T('Një klauzolë e keqe kthehet si kontest ligjor. Paguan shtrenjtë dhe publikisht.', 'One bad clause comes back as a legal dispute. You pay dearly and publicly.') },
          good: { fx: { cashU: 0.3 }, res: T('Askush nuk i lexoi ndonjëherë. I shpëtove.', 'Nobody ever read them. You got away with it.') } } }),
    ],
  },
  {
    id: 'marketing', stage: [0, 5], weight: 6,
    req: (s) => s.revenue > 0,
    title: T('Si të njihen', 'How they find you'),
    body: T('Produkti i mirë nuk shitet vetë. Dikush duhet ta dëgjojë emrin tënd para se ta besojë.',
            'A good product does not sell itself. Someone has to hear your name before they trust it.'),
    opts: [
      O(T('Reklamë e paguar', 'Paid advertising'), T('Rritje e blerë, e ndalon kur ndalon pagesa.', 'Bought growth, stops when payment stops.'),
        { cashU: -1.3, revU: 1.1, rep: 2 },
        T('Numrat lëvizin ndërsa buxheti digjet. Kur e fike, u ndal edhe rritja.',
          'The numbers move while the budget burns. When you switch it off, growth stops too.')),
      O(T('Përmbajtje dhe reputacion', 'Content and reputation'), T('E ngadaltë, përbëhet me kohë.', 'Slow, compounds over time.'),
        { rep: 10, influence: 6, revU: 0.4, stress: 4 },
        T('Tre muaj asgjë. Pastaj njerëzit nisin të thonë emrin tënd në takime ku ti nuk je.',
          'Three months of nothing. Then people start saying your name in rooms you are not in.')),
      O(T('Partneritet me një emër', 'Partner with a name'), T('Besueshmëri e huazuar.', 'Borrowed credibility.'),
        { influence: 10, revU: 0.8, equity: -3, rep: 6 },
        T('Logo e tyre pranë të tundës hap dyer që nuk hapeshin. Edhe pritshmëri që duhen mbajtur.',
          'Their logo next to yours opens doors that were shut. And expectations you must now meet.')),
    ],
  },
  {
    id: 'overwork', stage: [0, 6], weight: 5,
    req: (s) => s.stress > 45,
    title: T('Java e gjashtëdhjetë orëve', 'The sixty-hour week'),
    body: T('Trupi po dërgon fatura të vogla: gjumi, shpina, durimi. Ti po i shtyn për më vonë.',
            'Your body is sending small invoices: sleep, back, patience. You keep deferring them.'),
    opts: [
      O(T('Shtyj edhe pak', 'Push harder'), T('Rritje tani, faturë më vonë.', 'Growth now, bill later.'),
        { revMult: 1.12, stress: 16, morale: -5 },
        T('Funksionon. Gjithmonë funksionon — derisa një ditë nuk funksionon më.',
          'It works. It always works — until one day it does not.')),
      O(T('Merr dy javë pushim', 'Take two weeks off'), T('Humb vrull, fiton kokë të kthjellët.', 'Lose momentum, gain a clear head.'),
        { stress: -26, revMult: 0.96, morale: 8 },
        T('Bota nuk u shemb pa ty. Ky ishte mësimi më i shtrenjtë dhe më i lirë njëkohësisht.',
          'The world did not collapse without you. The most expensive and cheapest lesson at once.')),
      O(T('Delego gjithçka që mundesh', 'Delegate everything you can'), T('Kosto më e lartë, kokë më e lirë.', 'Higher cost, lighter head.'),
        { team: 1, stress: -14, morale: 6, cashU: -0.6 },
        T('Të tjerët e bëjnë 80% aq mirë sa ti. Mëson se 80% mjafton.',
          'Others do it 80% as well as you. You learn that 80% is enough.')),
    ],
  },
];

export default EARLY;
